[package]
name = "dolev-strong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1.0.1"
rand = "0.7.0"
tokio = { version = "1", features = ["full"] }
